// Cache toàn bộ DOM element của app (index.html). Chỉ import ở trang app, không ở login.
export const els = {
  appShell: document.getElementById('appShell'),
  sidebarToggleBtn: document.getElementById('sidebarToggleBtn'),
  sidebarExpandBtn: document.getElementById('sidebarExpandBtn'),
  sidebarOverlay: document.getElementById('sidebarOverlay'),
  pageTitle: document.getElementById('pageTitle'),
  pageDesc: document.getElementById('pageDesc'),
  globalNotice: document.getElementById('globalNotice'),
  scanTickToast: document.getElementById('scanTickToast'),
  scanTickText: document.getElementById('scanTickText'),
  userBadge: document.getElementById('userBadge'),

  navItems: Array.from(document.querySelectorAll('.nav-item')),
  viewPanels: Array.from(document.querySelectorAll('[data-view-panel]')),

  cameraGrid: document.getElementById('cameraGrid'),
  cameraForm: document.getElementById('cameraForm'),
  cameraName: document.getElementById('cameraName'),
  cameraUrl: document.getElementById('cameraUrl'),

  focusPanel: document.getElementById('focusPanel'),
  focusTitle: document.getElementById('focusTitle'),
  focusMeta: document.getElementById('focusMeta'),
  focusVideo: document.getElementById('focusVideo'),
  focusStreamStatus: document.getElementById('focusStreamStatus'),
  focusCanvas: document.getElementById('focusCanvas'),
  focusPlaceholder: document.getElementById('focusPlaceholder'),
  focusCloseBtn: document.getElementById('focusCloseBtn'),
  focusFullscreenBtn: document.getElementById('focusFullscreenBtn'),

  cameraEditModal: document.getElementById('cameraEditModal'),
  cameraEditForm: document.getElementById('cameraEditForm'),
  cameraEditCameraId: document.getElementById('cameraEditCameraId'),
  cameraEditName: document.getElementById('cameraEditName'),
  cameraEditUrl: document.getElementById('cameraEditUrl'),
  cameraEditEnabled: document.getElementById('cameraEditEnabled'),
  cameraEditCancelBtn: document.getElementById('cameraEditCancelBtn'),
  cameraEditCloseBtn: document.getElementById('cameraEditCloseBtn'),

  sessionBody: document.getElementById('sessionBody'),
  plateBody: document.getElementById('plateBody'),
  mCamerasTotal: document.getElementById('mCamerasTotal'),
  mCamerasOn: document.getElementById('mCamerasOn'),
  mActive: document.getElementById('mActive'),
  mCheckin: document.getElementById('mCheckin'),
  mCheckout: document.getElementById('mCheckout'),
  mOccupancy: document.getElementById('mOccupancy'),
  mOccupancyBar: document.getElementById('mOccupancyBar'),
  mRevenue: document.getElementById('mRevenue'),
  overviewLotList: document.getElementById('overviewLotList'),

  historyActiveOnly: document.getElementById('historyActiveOnly'),
  historyLimit: document.getElementById('historyLimit'),
  historyRefreshBtn: document.getElementById('historyRefreshBtn'),
  historySessionBody: document.getElementById('historySessionBody'),
  historyPlateBody: document.getElementById('historyPlateBody'),
  sessionsSearch: document.getElementById('sessionsSearch'),
  platesSearch: document.getElementById('platesSearch'),
  platesRefreshBtn: document.getElementById('platesRefreshBtn'),

  reportsDays: document.getElementById('reportsDays'),
  reportsRefreshBtn: document.getElementById('reportsRefreshBtn'),
  rpRevenue: document.getElementById('rpRevenue'),
  rpSessions: document.getElementById('rpSessions'),
  rpAvgDuration: document.getElementById('rpAvgDuration'),
  rpPeakHour: document.getElementById('rpPeakHour'),
  dailyChartCanvas: document.getElementById('dailyChartCanvas'),
  hourChartCanvas: document.getElementById('hourChartCanvas'),

  logHours: document.getElementById('logHours'),
  logLimit: document.getElementById('logLimit'),
  logAutoRefresh: document.getElementById('logAutoRefresh'),
  logRefreshBtn: document.getElementById('logRefreshBtn'),
  logBody: document.getElementById('logBody'),

  rfidForm: document.getElementById('rfidForm'),
  rfidCard: document.getElementById('rfidCard'),
  rfidDirection: document.getElementById('rfidDirection'),
  rfidLot: document.getElementById('rfidLot'),
  rfidPlate: document.getElementById('rfidPlate'),
  rfidSource: document.getElementById('rfidSource'),
  rfidLogBody: document.getElementById('rfidLogBody'),

  rfidCardForm: document.getElementById('rfidCardForm'),
  rfidCardId: document.getElementById('rfidCardId'),
  rfidCardPlate: document.getElementById('rfidCardPlate'),
  rfidCardOwner: document.getElementById('rfidCardOwner'),
  rfidCardBody: document.getElementById('rfidCardBody'),

  lotForm: document.getElementById('lotForm'),
  lotFormTitle: document.getElementById('lotFormTitle'),
  lotEditId: document.getElementById('lotEditId'),
  lotName: document.getElementById('lotName'),
  lotCapacity: document.getElementById('lotCapacity'),
  lotEntryCamera: document.getElementById('lotEntryCamera'),
  lotExitCamera: document.getElementById('lotExitCamera'),
  lotIsActive: document.getElementById('lotIsActive'),
  lotAiEnabled: document.getElementById('lotAiEnabled'),
  lotRfidPort: document.getElementById('lotRfidPort'),
  lotSubmitBtn: document.getElementById('lotSubmitBtn'),
  lotCancelEditBtn: document.getElementById('lotCancelEditBtn'),
  lotBody: document.getElementById('lotBody'),
  snapshotLotFilter: document.getElementById('snapshotLotFilter'),
  snapshotRefreshBtn: document.getElementById('snapshotRefreshBtn'),
  snapshotBody: document.getElementById('snapshotBody'),
  lotDetailTitle: document.getElementById('lotDetailTitle'),
  lotDetailMeta: document.getElementById('lotDetailMeta'),
  lotDetailAiToggle: document.getElementById('lotDetailAiToggle'),
  lotDetailCloseBtn: document.getElementById('lotDetailCloseBtn'),
  lotEntryVideo: document.getElementById('lotEntryVideo'),
  lotEntryStreamStatus: document.getElementById('lotEntryStreamStatus'),
  lotEntryCanvas: document.getElementById('lotEntryCanvas'),
  lotEntryPlaceholder: document.getElementById('lotEntryPlaceholder'),
  lotExitVideo: document.getElementById('lotExitVideo'),
  lotExitStreamStatus: document.getElementById('lotExitStreamStatus'),
  lotExitCanvas: document.getElementById('lotExitCanvas'),
  lotExitPlaceholder: document.getElementById('lotExitPlaceholder'),
  lotEntryCaptureImg: document.getElementById('lotEntryCaptureImg'),
  lotExitCaptureRefImg: document.getElementById('lotExitCaptureRefImg'),
  lotExitCaptureImg: document.getElementById('lotExitCaptureImg'),
  lotEntryCaptureStatus: document.getElementById('lotEntryCaptureStatus'),
  lotExitCaptureStatus: document.getElementById('lotExitCaptureStatus'),
  lotDetailLogBody: document.getElementById('lotDetailLogBody'),

  aiUploadForm: document.getElementById('aiUploadForm'),
  aiModelFile: document.getElementById('aiModelFile'),
  aiStatusText: document.getElementById('aiStatusText'),
  aiModelsList: document.getElementById('aiModelsList'),
  aiCameraSelect: document.getElementById('aiCameraSelect'),
  aiLiveStartBtn: document.getElementById('aiLiveStartBtn'),
  aiLiveStopBtn: document.getElementById('aiLiveStopBtn'),
  aiLiveCanvas: document.getElementById('aiLiveCanvas'),
  aiLivePlaceholder: document.getElementById('aiLivePlaceholder'),
  aiLiveStatus: document.getElementById('aiLiveStatus'),

  userStateText: document.getElementById('userStateText'),
  logoutBtn: document.getElementById('logoutBtn'),
  changePwForm: document.getElementById('changePwForm'),
  cpOld: document.getElementById('cpOld'),
  cpNew: document.getElementById('cpNew'),
  cpConfirm: document.getElementById('cpConfirm'),
  cpError: document.getElementById('cpError'),
  resetPwForm: document.getElementById('resetPwForm'),
  resetUser: document.getElementById('resetUser'),
  resetNew: document.getElementById('resetNew'),
  resetError: document.getElementById('resetError'),

  settingsForm: document.getElementById('settingsForm'),
  refreshSeconds: document.getElementById('refreshSeconds'),
  autoRefresh: document.getElementById('autoRefresh'),
  apiBaseReadonly: document.getElementById('apiBaseReadonly'),

  healthCheckBtn: document.getElementById('healthCheckBtn'),
  healthResult: document.getElementById('healthResult')
};
